version: "3.9"
services:
  db:
    image: mariadb:10.3.32
    command: --default-authentication-plugin=mysql_native_password
    hostname: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: USERS
      MYSQL_USER: user
      MYSQL_PASSWORD: password